package Main;

public enum GameRequest {
    CREATE_BUILDING,
    CREATE_UNIT_IN_BUILDING,
    CREATE_UNIT,
    CHANGE_UNIT_STATE,
    DISBAND,
    MODIFY_GATE,
    CHANGE_PRODUCT,
    REPAIR,
    GET_RESOURCE,
    FREE_STOCKPILE_SPACE,
    CHANGE_MONEY,
    ADD_TO_STOCKPILE,
    REMOVE_FROM_STOCKPILE,
    SELECT_UNITS,
    SELECT_BUILDING,
    MOVE_UNIT,


    ;
}
