package Main;

public enum NormalRequest {
    SIGNUP,
    REMOVE_SLOGAN,
    CHANGE_PROFILE_FIELDS,
    CHANGE_PASSWORD,
    GET_USER_BY_USERNAME,
    SEND_GLOBAL_MESSAGE,
    RECEIVE_GLOBAL_MESSAGE,
    SEND_PRIVATE_MESSAGE,
    CREATE_ROOM,
    MAP_NAME,
    GET_MAP,
    CHECK_MAP_NAME,
    SAVE_MAP,
    SEND_ROOM_MESSAGE,
    ADD_ROOM_TO_CLIENT,
    ;
}
