package Main;

public enum NormalRequest {
    SIGNUP,
    REMOVE_SLOGAN,
    CHANGE_PROFILE_FIELDS,
    CHANGE_PASSWORD,
    GET_USER_BY_USERNAME,
    SEND_GLOBAL_MESSAGE,
    GET_USERS_DATA,
    SEND_FRIEND_REQUSET,
    LOAD_ALL_USERS_DATA,
    SUBMIT_FRIENDSHIP,
    ;
}
